version: '3.8'

services:
  professores-service:
    build:
      context: ./professores-service
    ports:
      - "8080:8080"

  disciplinas-service:
    build:
      context: ./disciplinas-service
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - professores-service
      - disciplinas-service
